### ISSUE TITLE
Examples没办法跑啊

### ISSUE THREAD

**Issue by xfworld** [amazeui/amazeui-react#86]
@minwe 
以下是相关的错误信息：
> gulp "examples"

[10:47:31] Requiring external module babel-core/register
[10:47:41] Using gulpfile ~/WebstormProjects/amazeui-react/gulpfile.babel.js
[10:47:41] Task 'examples' is not in your gulpfile
[10:47:41] Please check the documentation for proper gulpfile formatting

在gulpfile.babel.js里面都没有找到相关的定义啊，是不是写掉了？

**Comment by minwe** [comment]
哪里写了 `gulp examples`？

```
npm run examples
```

**Comment by xfworld** [comment]
npm run examples 
其实执行后，会自动的调度gulp examples，，要看执行过程么？接下来和上面的结果一样了....

难道是我什么地方配置错了？ @minwe

**Comment by minwe** [comment]
更新代码，你的可能是原来老的。

**Comment by xfworld** [comment]
我晕，我才fork的代码啊...早上10：00....
@minwe  我崩溃了..

**Comment by xfworld** [comment]
npm run examples

> amazeui-react@1.0.0-beta2 examples /home/xfworld/WebstormProjects/amazeui-react
> gulp examples

[11:19:35] Requiring external module babel-core/register
[11:22:03] Using gulpfile ~/WebstormProjects/amazeui-react/gulpfile.babel.js
[11:22:03] Task 'examples' is not in your gulpfile
[11:22:03] Please check the documentation for proper gulpfile formatting

npm ERR! Linux 3.13.0-68-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "examples"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! amazeui-react@1.0.0-beta2 examples: `gulp examples`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the amazeui-react@1.0.0-beta2 examples script 'gulp examples'.
npm ERR! This is most likely a problem with the amazeui-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp examples
npm ERR! You can get their info via:
npm ERR!     npm owner ls amazeui-react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xfworld/WebstormProjects/amazeui-react/npm-debug.log

**Comment by minwe** [comment]
不可能吧。

https://github.com/amazeui/amazeui-react/blob/master/package.json#L11

你对比一下本地文件和这个一样吗？

**Comment by xfworld** [comment]
就是这个不一样....

**Comment by xfworld** [comment]
现在的编译环境又换成webpack了？

**Comment by xfworld** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'examples' ]
2 info using npm@2.14.7
3 info using node@v4.2.2
4 verbose run-script [ 'preexamples', 'examples', 'postexamples' ]
5 info preexamples amazeui-react@1.0.0-beta2
6 info examples amazeui-react@1.0.0-beta2
7 verbose unsafe-perm in lifecycle true
8 info amazeui-react@1.0.0-beta2 Failed to exec examples script
9 verbose stack Error: amazeui-react@1.0.0-beta2 examples: `node ./examples/server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid amazeui-react@1.0.0-beta2
11 verbose cwd /home/xfworld/WebstormProjects/amazeui-react
12 error Linux 3.13.0-68-generic
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "examples"
14 error node v4.2.2
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error amazeui-react@1.0.0-beta2 examples: `node ./examples/server.js`
17 error Exit status 1
18 error Failed at the amazeui-react@1.0.0-beta2 examples script 'node ./examples/server.js'.
18 error This is most likely a problem with the amazeui-react package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./examples/server.js
18 error You can get their info via:
18 error     npm owner ls amazeui-react
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

最后还是跑不起来....

**Comment by minwe** [comment]
你自己的仓库里的代码不是最新，直接从官方项目克隆或者重新 fork。

**Comment by xfworld** [comment]
npm run examples

> amazeui-react@1.0.0 examples /home/xfworld/WebstormProjects/amazeui-react
> node ./examples/server.js

/home/xfworld/WebstormProjects/amazeui-react/examples
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch . ENOSPC
    at exports._errnoException (util.js:874:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/home/xfworld/WebstormProjects/amazeui-react/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/xfworld/WebstormProjects/amazeui-react/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/xfworld/WebstormProjects/amazeui-react/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/xfworld/WebstormProjects/amazeui-react/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/xfworld/WebstormProjects/amazeui-react/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/xfworld/WebstormProjects/amazeui-react/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:82:15)

@minwe  今天又试了一把，还是报错。直接从主仓库获取的最新代码.....

**Comment by minwe** [comment]
有可能是文件系统同时打开文件数量限制。

参考设置一下：

http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

**Comment by xfworld** [comment]
终于好了，谢谢@minew

果然是监控文件数太小了
